#!/bin/bash
#
# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (c) 2021-2022, Antonio Niño Díaz

set -e

SCRIPT=`realpath $0`
IN=`dirname $SCRIPT`

echo ""
echo "[*] Converting ${IN}..."
echo ""

# Prepare destination folder

OUT_DIR=built_assets
rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}

GRAPHICS="${PWD}/graphics"

# Convert graphics

mkdir ${OUT_DIR}/graphics
pushd ${OUT_DIR}/graphics

${SUPERFAMICONV} palette \
    --mode gba \
    --palettes 10 \
    --colors 16 \
    --color-zero 000000 \
    --in-image ${GRAPHICS}/city.png \
    --out-data city_palette.bin \
    --out-image city_palette.png \
    --verbose

${SUPERFAMICONV} tiles \
    --mode gba \
    --bpp 4 \
    --tile-width 8 --tile-height 8 \
    --max-tiles 512 \
    --in-image ${GRAPHICS}/city.png \
    --in-palette city_palette.bin \
    --out-data city_tiles.bin \
    --no-flip \
    --verbose

${SUPERFAMICONV} map \
    --mode gba \
    --bpp 4 \
    --tile-width 8 --tile-height 8 \
    --tile-base-offset 0 \
    --palette-base-offset 0 \
    --map-width 64 --map-height 64 \
    --split-width 64 --split-height 64 \
    --in-image ${GRAPHICS}/city.png \
    --in-palette city_palette.bin \
    --in-tiles city_tiles.bin \
    --out-data city_map.bin \
    --no-flip \
    --verbose

popd

# Convert binary files generated by other stages

for dir in $(find built_assets -type d)
do
    for f in $(find $dir -maxdepth 1 -iname *.bin)
    do
        ${BIN2C} "$f" "$dir"
    done
done

# Done!

exit 0
