// SPDX-License-Identifier: MIT
//
// Copyright (c) 2020-2022 Antonio Niño Díaz

// Example of how to load an affine background

#include <ugba/ugba.h>

#include "graphics/city_map_bin.h" // Autogenerated from city.png
#include "graphics/city_palette_bin.h"
#include "graphics/city_tiles_bin.h"

#define CITY_TILES_BASE     MEM_BG_TILES_BLOCK_ADDR(0)
#define CITY_MAP_BASE       MEM_BG_MAP_BLOCK_ADDR(8)

void copy_map_to_sbb(const void *source, void *dest, int width, int height)
{
    uint16_t *src_ptr = (uint16_t *)source;
    uint16_t *dst_ptr = (uint16_t *)dest;

    for (int j = 0; j < height; j++)
    {
        for (int i = 0; i < width; i++)
        {
            int index = 0;

            if (i >= 32)
                index += 32 * 32;
            if (j >= 32)
                index += 32 * 64;

            index += i % 32;
            index += (j % 32) * 32;

            dst_ptr[index] = *src_ptr++;
        }
    }
}

int main(int argc, char *argv[])
{
    UGBA_Init(&argc, &argv);

    // Enable interrupts. This is needed for SWI_VBlankIntrWait() to work.
    IRQ_Enable(IRQ_VBLANK);

    // Load the palette
    VRAM_BGPalette256Copy(city_palette_bin, city_palette_bin_size);

    // Load the tiles
    SWI_CpuSet_Copy16(city_tiles_bin, (void *)CITY_TILES_BASE,
                      city_tiles_bin_size);

    // Load the map
    copy_map_to_sbb(city_map_bin, (void *)CITY_MAP_BASE, 32, 32);

    // Setup background
    BG_AffineInit(2, BG_AFFINE_256x256, CITY_TILES_BASE, CITY_MAP_BASE, 0);

    int x = 100, y = -7;
    int angle = 0x20;

    bg_affine_src bg_src_start = {
        x << 8, y << 8,
        0, 0,
        1 << 8, 1 << 8,
        angle << 8
    };

    bg_affine_dst bg_dst;

    SWI_BgAffineSet(&bg_src_start, &bg_dst, 1);

    BG_AffineTransformSet(2, &bg_dst);

    // Set the display to mode 2 so that background 2 is affine, and turn it on.
    DISP_ModeSet(2);
    DISP_LayersEnable(0, 0, 1, 0, 0);

    while (1)
    {
        SWI_VBlankIntrWait();

        KEYS_Update();

        uint16_t keys = KEYS_Held();

        if (keys & KEY_UP)
            y--;
        else if (keys & KEY_DOWN)
            y++;

        if (keys & KEY_RIGHT)
            x++;
        else if (keys & KEY_LEFT)
            x--;

        if (keys & KEY_L)
            angle++;
        else if (keys & KEY_R)
            angle--;

        if (keys & KEY_A)
            BG_AffineWrapEnable(2, 1);
        else if (keys & KEY_B)
            BG_AffineWrapEnable(2, 0);

        if (keys & KEY_START)
        {
            BG_AffineWrapEnable(2, 1);
            angle = 50;
            x = 130;
            y = 25;
        }

        bg_affine_src bg_src = {
            x << 8, y << 8,
            0, 0,
            1 << 8, 1 << 8,
            angle << 8
        };

        SWI_BgAffineSet(&bg_src, &bg_dst, 1);

        BG_AffineTransformSet(2, &bg_dst);
    }
}
