#!/bin/bash
#
# SPDX-License-Identifier: GPL-3.0-only
#
# Copyright (c) 2021-2022, Antonio Niño Díaz

set -e

SCRIPT=`realpath $0`
IN=`dirname $SCRIPT`

echo ""
echo "[*] Converting ${IN}..."
echo ""

# Prepare destination folder

OUT_DIR=built_assets
rm -rf ${OUT_DIR}
mkdir ${OUT_DIR}

GRAPHICS="${PWD}/graphics"

# Convert graphics

mkdir ${OUT_DIR}/graphics
pushd ${OUT_DIR}/graphics

grit ${GRAPHICS}/city.png -ftc -o city

${SUPERFAMICONV} palette \
    --mode gba \
    --palettes 1 \
    --colors 16 \
    --color-zero 000000 \
    --in-image ${GRAPHICS}/ball_red.png \
    --out-data ball_red_palette.bin \
    --out-image ball_red_palette.png \
    --verbose

${SUPERFAMICONV} tiles \
    --mode gba \
    --bpp 4 \
    --tile-width 8 --tile-height 8 \
    --in-image ${GRAPHICS}/ball_red.png \
    --in-palette ball_red_palette.bin \
    --out-data ball_red_tiles.bin \
    --verbose

${SUPERFAMICONV} palette \
    --mode gba \
    --palettes 1 \
    --colors 16 \
    --color-zero 000000 \
    --in-image ${GRAPHICS}/ball_green.png \
    --out-data ball_green_palette.bin \
    --out-image ball_green_palette.png \
    --verbose

${SUPERFAMICONV} tiles \
    --mode gba \
    --bpp 4 \
    --tile-width 8 --tile-height 8 \
    --in-image ${GRAPHICS}/ball_green.png \
    --in-palette ball_green_palette.bin \
    --out-data ball_green_tiles.bin \
    --verbose

popd

# Convert binary files generated by other stages

for dir in $(find built_assets -type d)
do
    for f in $(find $dir -maxdepth 1 -iname *.bin)
    do
        ${BIN2C} "$f" "$dir"
    done
done

# Done!

exit 0
